version: '3.8'

services:
  travel-agency:
    build: .
    ports:
      - "5173:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - .env.local
    volumes:
      - ./.env.local:/app/.env.local:ro
    container_name: travel-agency
    restart: unless-stopped
